/**
 * bundleExportService — assembles the InDesign hand-off zip.
 * Vitaly §10. Uses originals; never web copies (rule 15).
 * Signed URL uses the internal render secret (env accepts both INTERNAL_RENDER_SECRET and legacy INTERNAL_RENDER_KEY names — see env.ts) as HMAC key per rule 20 and Sam Phase 3 finding #2.
 */
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import JSZip from "jszip";
import {
  AssembledLayoutSchema,
  ArticlesSchema,
  ImagesSchema,
  type BundleManifest,
  type BundleBlock,
} from "@newsforge/shared/schemas";
import { prisma } from "../db.js";
import { env } from "../env.js";

const README_TEMPLATE = String.raw`# {{clientName}} — {{monthLabel}} Newsletter

**Run ID:** \`{{runId}}\`
**Template:** {{templateName}} (\`{{templateId}}\`)
**Layout version:** {{layoutVersion}}
**Generated:** {{generatedAt}} (UTC)

This bundle is a hand-off from NewsForge to your InDesign artboard. It contains
everything you need to reconstruct the newsletter at print quality without
touching the web app.

---

## What's in this zip

| Folder / file    | What it is                                                                          |
| ---------------- | ----------------------------------------------------------------------------------- |
| \`layout.json\`    | The full block-by-block layout the app produced. See "Reading \`layout.json\`" below. |
| \`text/\`          | One \`.txt\` file per text block. Filename = block id in \`layout.json\`.               |
| \`images/\`        | Original uploaded images at full resolution. Filename = block id.                   |
| \`fonts/\`         | Google-Font fallbacks for the client's brand fonts.                                 |

## Page geometry

- **Trim:** 11 × 17 in (folded spread)
- **Bleed:** {{bleedInches}} in all sides — total page is 11.25 × 17.25 in
- **Safe area:** {{safeAreaInches}} in inside the trim
- **Crop marks:** {{cropMarksLabel}}

## Reading \`layout.json\`

\`layout.json\` is a BundleManifest. The important field is \`blocks[]\`. Each block has:

- \`blockId\` — the id used to name the text/image file in this bundle.
- \`slotId\` — the template's slot id.
- \`page\` — 1-indexed page number within the spread.
- \`position\` — \`{ col, row, colSpan, rowSpan }\` on a 12-column grid, 10 rows per page.
- \`kind\` — one of \`article | image | filler | placeholder | recurring | empty\`.
- \`textFile\` / \`imageFile\` — the file in this bundle to pull content from.
- \`styleTag\` — optional hint (\`hero\`, \`hero-portrait\`, \`panorama\`, \`cover\`, \`photo-placeholder\`).

## Suggested InDesign steps

1. Open your client master for {{clientName}} (or start fresh at 11 × 17 in, 0.125 in bleed).
2. Drop a 12-column × 10-row grid guide on page 1.
3. For each block in \`layout.json\` where \`page === 1\`:
   a. Draw a frame at \`(col, row)\` spanning \`(colSpan, rowSpan)\`.
   b. If \`textFile\` is set, place \`text/{{blockId}}.txt\`.
   c. If \`imageFile\` is set, place \`images/{{blockId}}.<ext>\`.
   d. Apply the paragraph/object style that matches \`styleTag\` (or \`kind\`).
4. Repeat for pages 2..N.
5. Placeholder blocks are intentionally empty — drop a photo of your own or leave as-is.

## Notes

- Any \`text/*.txt\` ending with \`<!-- AI FILLER -->\` was generated by NewsForge's filler engine.
- Any block whose original article was truncated is noted in \`layout.json.articleFit[].trimmed === true\`.
- Compliance concerns are in the run record's \`complianceFlags\` (query the API to fetch).

## Questions

If you need the run reopened in the web app, share the Run ID above.
Layout version {{layoutVersion}} is what this bundle was built from — later edits need a fresh export.
`;

function renderReadme(vars: Record<string, string | number>): string {
  return README_TEMPLATE.replace(/\{\{(\w+)\}\}/g, (_m, k: string) => {
    const v = vars[k];
    return v === undefined ? "" : String(v);
  });
}

// ---- Signed URL helper (Vitaly rule 20) ----

const SIGN_TTL_MS = 15 * 60 * 1000; // 15min per Sam security review (PHI-adjacent content)

export function signBundlePath(relativePath: string, now = Date.now()): {
  url: string;
  expiresAt: number;
} {
  const exp = now + SIGN_TTL_MS;
  const payload = `${relativePath}:${exp}`;
  const sig = crypto
    .createHmac("sha256", env.INTERNAL_RENDER_KEY)
    .update(payload)
    .digest("hex");
  const url =
    `${env.PUBLIC_BASE_URL.replace(/\/$/, "")}/exports/${relativePath}` +
    `?exp=${exp}&sig=${sig}`;
  return { url, expiresAt: exp };
}

export function verifyBundleSignature(
  relativePath: string,
  exp: number,
  sig: string,
  now = Date.now(),
): boolean {
  if (!Number.isFinite(exp) || exp < now) return false;
  const payload = `${relativePath}:${exp}`;
  const expected = crypto
    .createHmac("sha256", env.INTERNAL_RENDER_KEY)
    .update(payload)
    .digest("hex");
  try {
    return crypto.timingSafeEqual(
      Buffer.from(expected, "hex"),
      Buffer.from(sig, "hex"),
    );
  } catch {
    return false;
  }
}

// ---- Bundle build ----

export interface BuildBundleResult {
  bundleUrl: string;
  zipRelPath: string; // relative to uploads root
  zipAbsPath: string;
  sizeBytes: number;
  layoutVersion: number;
  builtAt: Date;
  manifest: BundleManifest;
}

/**
 * Build (or reuse) the InDesign bundle for a run.
 * Cached by (runId, layoutVersion). Returns a fresh signed URL each call.
 */
export async function buildBundle(
  runId: string,
  options: { regenerate?: boolean } = {},
): Promise<BuildBundleResult | { error: string; status: 404 | 500 }> {
  const run = await prisma.newsletterRun.findUnique({
    where: { id: runId },
    include: { client: true, template: true },
  });
  if (!run) return { error: "run_not_found", status: 404 };

  const exportsDir = path.resolve(env.UPLOAD_DIR, run.id, "exports");
  await fs.mkdir(exportsDir, { recursive: true });
  const zipFilename = `${run.id}-indesign-${run.layoutVersion}.zip`;
  const zipAbsPath = path.join(exportsDir, zipFilename);
  const zipRelPath = `${run.id}/exports/${zipFilename}`;

  // Cache hit?
  if (
    !options.regenerate &&
    run.bundleZipPath &&
    run.bundleLayoutVersion === run.layoutVersion
  ) {
    try {
      const stat = await fs.stat(zipAbsPath);
      const signed = signBundlePath(zipRelPath);
      const layoutParsed = AssembledLayoutSchema.safeParse(run.assembledLayout);
      const manifest = buildManifest(run, layoutParsed.success ? layoutParsed.data.blocks : []);
      return {
        bundleUrl: signed.url,
        zipRelPath,
        zipAbsPath,
        sizeBytes: stat.size,
        layoutVersion: run.layoutVersion,
        builtAt: run.bundleBuiltAt ?? new Date(),
        manifest,
      };
    } catch {
      // fall through to rebuild
    }
  }

  const layoutParsed = AssembledLayoutSchema.safeParse(run.assembledLayout);
  const articlesParsed = ArticlesSchema.safeParse(run.articles);
  const imagesParsed = ImagesSchema.safeParse(run.images);
  if (!layoutParsed.success || !articlesParsed.success || !imagesParsed.success) {
    return { error: "invalid_run_state", status: 500 };
  }
  const layout = layoutParsed.data;
  const articlesById = new Map(articlesParsed.data.map((a) => [a.id, a]));
  const imagesById = new Map(imagesParsed.data.map((i) => [i.id, i]));

  const zip = new JSZip();
  const bundleBlocks: BundleBlock[] = [];

  for (const b of layout.blocks) {
    const block: BundleBlock = {
      blockId: b.blockId,
      slotId: b.slotId,
      page: b.page,
      kind: b.kind,
      position: b.position,
      styleTag: b.styleTag,
    };

    if ((b.kind === "article" || b.kind === "recurring" || b.kind === "filler") && b.articleId) {
      const article = articlesById.get(b.articleId);
      if (article) {
        const textFile = `text/${b.blockId}.txt`;
        const parts: string[] = [];
        if (article.byline) parts.push(`# ${article.byline}`);
        // Preserve paragraph breaks as blank lines (already \n\n in source).
        parts.push(article.body);
        if (article.isFiller) parts.push("<!-- AI FILLER -->");
        zip.file(textFile, parts.join("\n\n") + "\n");
        block.textFile = textFile;
      }
    } else if (b.kind === "filler" && b.inlineText) {
      const textFile = `text/${b.blockId}.txt`;
      zip.file(textFile, `${b.inlineText}\n\n<!-- AI FILLER -->\n`);
      block.textFile = textFile;
    } else if (b.kind === "image" && b.imageId) {
      const img = imagesById.get(b.imageId);
      if (img) {
        const original = await readOriginalImage(img.url);
        if (original) {
          const ext = original.ext;
          const imageFile = `images/${b.blockId}${ext}`;
          zip.file(imageFile, original.bytes);
          block.imageFile = imageFile;
        }
      }
    }
    bundleBlocks.push(block);
  }

  const manifest = buildManifest(run, layout.blocks, bundleBlocks);
  zip.file("layout.json", JSON.stringify(manifest, null, 2));

  const readme = renderReadme({
    clientName: run.client.name,
    monthLabel: run.monthLabel,
    runId: run.id,
    templateName: run.template.name,
    templateId: run.template.id,
    layoutVersion: run.layoutVersion,
    generatedAt: new Date().toISOString(),
    bleedInches: run.client.bleedInches,
    safeAreaInches: run.client.safeAreaInches,
    cropMarksLabel: run.client.cropMarksEnabled
      ? "Enabled — printed at corners."
      : "Disabled.",
  });
  zip.file("README.md", readme);

  // fonts/ — leave empty stub; JayJay may populate later. Include a note.
  zip.file(
    "fonts/README.txt",
    "Google Font fallbacks for the client's brand fonts.\n" +
      "This bundle intentionally omits binary font files; download from Google Fonts:\n" +
      "  EB Garamond: https://fonts.google.com/specimen/EB+Garamond\n" +
      "  Nunito Sans: https://fonts.google.com/specimen/Nunito+Sans\n",
  );

  const buf = await zip.generateAsync({ type: "nodebuffer" });
  await fs.writeFile(zipAbsPath, buf);

  const builtAt = new Date();
  await prisma.newsletterRun.update({
    where: { id: run.id },
    data: {
      bundleZipPath: path.relative(process.cwd(), zipAbsPath),
      bundleBuiltAt: builtAt,
      bundleLayoutVersion: run.layoutVersion,
    },
  });

  const signed = signBundlePath(zipRelPath);
  return {
    bundleUrl: signed.url,
    zipRelPath,
    zipAbsPath,
    sizeBytes: buf.byteLength,
    layoutVersion: run.layoutVersion,
    builtAt,
    manifest,
  };
}

async function readOriginalImage(
  urlOrPath: string,
): Promise<{ bytes: Buffer; ext: string } | null> {
  // Images stored as "/uploads/<filename>" -> resolve to UPLOAD_DIR.
  try {
    let filePath: string;
    if (urlOrPath.startsWith("/uploads/")) {
      filePath = path.resolve(env.UPLOAD_DIR, urlOrPath.slice("/uploads/".length));
    } else if (path.isAbsolute(urlOrPath)) {
      filePath = urlOrPath;
    } else {
      // Not a local file (e.g. mock image with remote URL); skip.
      return null;
    }
    const bytes = await fs.readFile(filePath);
    const ext = path.extname(filePath) || ".bin";
    return { bytes, ext };
  } catch {
    return null;
  }
}

function buildManifest(
  run: Awaited<ReturnType<typeof prisma.newsletterRun.findUnique>> & {
    client: { name: string; bleedInches: number; safeAreaInches: number; cropMarksEnabled: boolean };
    template: { name: string };
  },
  layoutBlocks: ReadonlyArray<{
    blockId: string;
    slotId: string;
    page: number;
    kind: string;
    position: { col: number; row: number; colSpan: number; rowSpan: number };
    styleTag?: string;
  }>,
  overrideBlocks?: BundleBlock[],
): BundleManifest {
  return {
    runId: run!.id,
    clientId: run!.clientId,
    clientName: run!.client.name,
    templateId: run!.templateId,
    templateName: run!.template.name,
    monthLabel: run!.monthLabel,
    layoutVersion: run!.layoutVersion,
    generatedAt: new Date().toISOString(),
    bleedInches: run!.client.bleedInches,
    safeAreaInches: run!.client.safeAreaInches,
    cropMarksEnabled: run!.client.cropMarksEnabled,
    pageCount: layoutBlocks.reduce((max, b) => Math.max(max, b.page), 1),
    blocks:
      overrideBlocks ??
      layoutBlocks.map(
        (b): BundleBlock => ({
          blockId: b.blockId,
          slotId: b.slotId,
          page: b.page,
          kind: b.kind as BundleBlock["kind"],
          position: b.position,
          styleTag: b.styleTag,
        }),
      ),
  };
}
